/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

/**
 * Internal Server Error
 */
export type UpdateBrainResponseBodyData = {
    httpMeta: components.HTTPMetadata;
};

/**
 * Internal Server Error
 */
export class UpdateBrainResponseBody extends Error {
    httpMeta: components.HTTPMetadata;

    /** The original data that was passed to this error instance. */
    data$: UpdateBrainResponseBodyData;

    constructor(err: UpdateBrainResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.httpMeta = err.httpMeta;

        this.name = "UpdateBrainResponseBody";
    }
}

/** @internal */
export const UpdateBrainResponseBody$inboundSchema: z.ZodType<
    UpdateBrainResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
    })
    .transform((v) => {
        const remapped = remap$(v, {
            HttpMeta: "httpMeta",
        });

        return new UpdateBrainResponseBody(remapped);
    });

/** @internal */
export type UpdateBrainResponseBody$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
};

/** @internal */
export const UpdateBrainResponseBody$outboundSchema: z.ZodType<
    UpdateBrainResponseBody$Outbound,
    z.ZodTypeDef,
    UpdateBrainResponseBody
> = z
    .instanceof(UpdateBrainResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z
            .object({
                httpMeta: components.HTTPMetadata$outboundSchema,
            })
            .transform((v) => {
                return remap$(v, {
                    httpMeta: "HttpMeta",
                });
            })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateBrainResponseBody$ {
    /** @deprecated use `UpdateBrainResponseBody$inboundSchema` instead. */
    export const inboundSchema = UpdateBrainResponseBody$inboundSchema;
    /** @deprecated use `UpdateBrainResponseBody$outboundSchema` instead. */
    export const outboundSchema = UpdateBrainResponseBody$outboundSchema;
    /** @deprecated use `UpdateBrainResponseBody$Outbound` instead. */
    export type Outbound = UpdateBrainResponseBody$Outbound;
}
