workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    athenaCopilot:
        inputs:
            - location: ../../../Downloads/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/shreyaan/shreyaan/athena-copilot
targets:
    my-first-target:
        target: typescript
        source: athenaCopilot
