/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateNewBrainRequestBody = {
    /**
     * Name of the brain
     */
    name: string;
};

export type CreateNewBrainResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    brain?: components.Brain | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace CreateNewBrainRequestBody$ {
    export const inboundSchema: z.ZodType<CreateNewBrainRequestBody, z.ZodTypeDef, unknown> =
        z.object({
            name: z.string(),
        });

    export type Outbound = {
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateNewBrainRequestBody> =
        z.object({
            name: z.string(),
        });
}

/** @internal */
export namespace CreateNewBrainResponse$ {
    export const inboundSchema: z.ZodType<CreateNewBrainResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Brain: components.Brain$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Brain: "brain",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Brain?: components.Brain$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateNewBrainResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            brain: components.Brain$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                brain: "Brain",
                headers: "Headers",
            });
        });
}
