/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type DeleteChatChatIdRequest = {
    chatId: string;
};

export type DeleteChatChatIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    deleteResponse?: components.DeleteResponse | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace DeleteChatChatIdRequest$ {
    export const inboundSchema: z.ZodType<DeleteChatChatIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            chat_id: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                chat_id: "chatId",
            });
        });

    export type Outbound = {
        chat_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteChatChatIdRequest> = z
        .object({
            chatId: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                chatId: "chat_id",
            });
        });
}

/** @internal */
export namespace DeleteChatChatIdResponse$ {
    export const inboundSchema: z.ZodType<DeleteChatChatIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            DeleteResponse: components.DeleteResponse$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                DeleteResponse: "deleteResponse",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        DeleteResponse?: components.DeleteResponse$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteChatChatIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            deleteResponse: components.DeleteResponse$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                deleteResponse: "DeleteResponse",
                headers: "Headers",
            });
        });
}
