/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type DownloadDocumentRequest = {
    brainId: string;
    documentId: string;
};

/**
 * OK
 */
export type DownloadDocumentResponseBody = {
    /**
     * The URL to download the document file. This URL is a pre-signed URL that provides temporary access to the document file hosted on a cloud storage service.
     */
    url?: string | undefined;
};

export type DownloadDocumentResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: DownloadDocumentResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace DownloadDocumentRequest$ {
    export const inboundSchema: z.ZodType<DownloadDocumentRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
            document_id: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                brain_id: "brainId",
                document_id: "documentId",
            });
        });

    export type Outbound = {
        brain_id: string;
        document_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadDocumentRequest> = z
        .object({
            brainId: z.string(),
            documentId: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                brainId: "brain_id",
                documentId: "document_id",
            });
        });
}

/** @internal */
export namespace DownloadDocumentResponseBody$ {
    export const inboundSchema: z.ZodType<DownloadDocumentResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            url: z.string().optional(),
        });

    export type Outbound = {
        url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadDocumentResponseBody> =
        z.object({
            url: z.string().optional(),
        });
}

/** @internal */
export namespace DownloadDocumentResponse$ {
    export const inboundSchema: z.ZodType<DownloadDocumentResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => DownloadDocumentResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: DownloadDocumentResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadDocumentResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => DownloadDocumentResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                headers: "Headers",
            });
        });
}
