/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetAllDocumentsRequest = {
    brainId: string;
};

export type GetAllDocumentsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    documents?: Array<components.Document> | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetAllDocumentsRequest$ {
    export const inboundSchema: z.ZodType<GetAllDocumentsRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                brain_id: "brainId",
            });
        });

    export type Outbound = {
        brain_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAllDocumentsRequest> = z
        .object({
            brainId: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                brainId: "brain_id",
            });
        });
}

/** @internal */
export namespace GetAllDocumentsResponse$ {
    export const inboundSchema: z.ZodType<GetAllDocumentsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Documents: z.array(components.Document$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Documents: "documents",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Documents?: Array<components.Document$.Outbound> | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAllDocumentsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            documents: z.array(components.Document$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                documents: "Documents",
                headers: "Headers",
            });
        });
}
