/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetBrainBrainIdRequest = {
    brainId: string;
};

/**
 * OK
 */
export type GetBrainBrainIdResponseBody = {};

export type GetBrainBrainIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: GetBrainBrainIdResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetBrainBrainIdRequest$ {
    export const inboundSchema: z.ZodType<GetBrainBrainIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
        })
        .transform((v) => {
            return {
                brainId: v.brain_id,
            };
        });

    export type Outbound = {
        brain_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBrainBrainIdRequest> = z
        .object({
            brainId: z.string(),
        })
        .transform((v) => {
            return {
                brain_id: v.brainId,
            };
        });
}

/** @internal */
export namespace GetBrainBrainIdResponseBody$ {
    export const inboundSchema: z.ZodType<GetBrainBrainIdResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBrainBrainIdResponseBody> =
        z.object({});
}

/** @internal */
export namespace GetBrainBrainIdResponse$ {
    export const inboundSchema: z.ZodType<GetBrainBrainIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetBrainBrainIdResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetBrainBrainIdResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBrainBrainIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetBrainBrainIdResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
