/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetChatbotAnalyticsRequest = {
    chatbotId?: string | undefined;
};

/**
 * OK
 */
export type GetChatbotAnalyticsResponseBody = {};

export type GetChatbotAnalyticsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: GetChatbotAnalyticsResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetChatbotAnalyticsRequest$ {
    export const inboundSchema: z.ZodType<GetChatbotAnalyticsRequest, z.ZodTypeDef, unknown> = z
        .object({
            chatbot_id: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.chatbot_id === undefined ? null : { chatbotId: v.chatbot_id }),
            };
        });

    export type Outbound = {
        chatbot_id?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChatbotAnalyticsRequest> = z
        .object({
            chatbotId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.chatbotId === undefined ? null : { chatbot_id: v.chatbotId }),
            };
        });
}

/** @internal */
export namespace GetChatbotAnalyticsResponseBody$ {
    export const inboundSchema: z.ZodType<GetChatbotAnalyticsResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetChatbotAnalyticsResponseBody
    > = z.object({});
}

/** @internal */
export namespace GetChatbotAnalyticsResponse$ {
    export const inboundSchema: z.ZodType<GetChatbotAnalyticsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetChatbotAnalyticsResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetChatbotAnalyticsResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChatbotAnalyticsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetChatbotAnalyticsResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
