/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetChatbotGetMessagesRequest = {
    chatbotId?: string | undefined;
};

export type GetChatbotGetMessagesResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    chatbotMessages?: components.ChatbotMessages | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export const GetChatbotGetMessagesRequest$inboundSchema: z.ZodType<
    GetChatbotGetMessagesRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        chatbot_id: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            chatbot_id: "chatbotId",
        });
    });

/** @internal */
export type GetChatbotGetMessagesRequest$Outbound = {
    chatbot_id?: string | undefined;
};

/** @internal */
export const GetChatbotGetMessagesRequest$outboundSchema: z.ZodType<
    GetChatbotGetMessagesRequest$Outbound,
    z.ZodTypeDef,
    GetChatbotGetMessagesRequest
> = z
    .object({
        chatbotId: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            chatbotId: "chatbot_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotGetMessagesRequest$ {
    /** @deprecated use `GetChatbotGetMessagesRequest$inboundSchema` instead. */
    export const inboundSchema = GetChatbotGetMessagesRequest$inboundSchema;
    /** @deprecated use `GetChatbotGetMessagesRequest$outboundSchema` instead. */
    export const outboundSchema = GetChatbotGetMessagesRequest$outboundSchema;
    /** @deprecated use `GetChatbotGetMessagesRequest$Outbound` instead. */
    export type Outbound = GetChatbotGetMessagesRequest$Outbound;
}

/** @internal */
export const GetChatbotGetMessagesResponse$inboundSchema: z.ZodType<
    GetChatbotGetMessagesResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
        ChatbotMessages: components.ChatbotMessages$inboundSchema.optional(),
        Headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            HttpMeta: "httpMeta",
            ChatbotMessages: "chatbotMessages",
            Headers: "headers",
        });
    });

/** @internal */
export type GetChatbotGetMessagesResponse$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
    ChatbotMessages?: components.ChatbotMessages$Outbound | undefined;
    Headers: { [k: string]: Array<string> };
};

/** @internal */
export const GetChatbotGetMessagesResponse$outboundSchema: z.ZodType<
    GetChatbotGetMessagesResponse$Outbound,
    z.ZodTypeDef,
    GetChatbotGetMessagesResponse
> = z
    .object({
        httpMeta: components.HTTPMetadata$outboundSchema,
        chatbotMessages: components.ChatbotMessages$outboundSchema.optional(),
        headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            httpMeta: "HttpMeta",
            chatbotMessages: "ChatbotMessages",
            headers: "Headers",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotGetMessagesResponse$ {
    /** @deprecated use `GetChatbotGetMessagesResponse$inboundSchema` instead. */
    export const inboundSchema = GetChatbotGetMessagesResponse$inboundSchema;
    /** @deprecated use `GetChatbotGetMessagesResponse$outboundSchema` instead. */
    export const outboundSchema = GetChatbotGetMessagesResponse$outboundSchema;
    /** @deprecated use `GetChatbotGetMessagesResponse$Outbound` instead. */
    export type Outbound = GetChatbotGetMessagesResponse$Outbound;
}
