/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetChatbotAnalyticsRequest = {
    chatbotId?: string | undefined;
};

export type GetChatbotAnalyticsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    chatbotAnalytics?: components.ChatbotAnalytics | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export const GetChatbotAnalyticsRequest$inboundSchema: z.ZodType<
    GetChatbotAnalyticsRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        chatbot_id: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            chatbot_id: "chatbotId",
        });
    });

/** @internal */
export type GetChatbotAnalyticsRequest$Outbound = {
    chatbot_id?: string | undefined;
};

/** @internal */
export const GetChatbotAnalyticsRequest$outboundSchema: z.ZodType<
    GetChatbotAnalyticsRequest$Outbound,
    z.ZodTypeDef,
    GetChatbotAnalyticsRequest
> = z
    .object({
        chatbotId: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            chatbotId: "chatbot_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotAnalyticsRequest$ {
    /** @deprecated use `GetChatbotAnalyticsRequest$inboundSchema` instead. */
    export const inboundSchema = GetChatbotAnalyticsRequest$inboundSchema;
    /** @deprecated use `GetChatbotAnalyticsRequest$outboundSchema` instead. */
    export const outboundSchema = GetChatbotAnalyticsRequest$outboundSchema;
    /** @deprecated use `GetChatbotAnalyticsRequest$Outbound` instead. */
    export type Outbound = GetChatbotAnalyticsRequest$Outbound;
}

/** @internal */
export const GetChatbotAnalyticsResponse$inboundSchema: z.ZodType<
    GetChatbotAnalyticsResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
        ChatbotAnalytics: components.ChatbotAnalytics$inboundSchema.optional(),
        Headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            HttpMeta: "httpMeta",
            ChatbotAnalytics: "chatbotAnalytics",
            Headers: "headers",
        });
    });

/** @internal */
export type GetChatbotAnalyticsResponse$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
    ChatbotAnalytics?: components.ChatbotAnalytics$Outbound | undefined;
    Headers: { [k: string]: Array<string> };
};

/** @internal */
export const GetChatbotAnalyticsResponse$outboundSchema: z.ZodType<
    GetChatbotAnalyticsResponse$Outbound,
    z.ZodTypeDef,
    GetChatbotAnalyticsResponse
> = z
    .object({
        httpMeta: components.HTTPMetadata$outboundSchema,
        chatbotAnalytics: components.ChatbotAnalytics$outboundSchema.optional(),
        headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            httpMeta: "HttpMeta",
            chatbotAnalytics: "ChatbotAnalytics",
            headers: "Headers",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotAnalyticsResponse$ {
    /** @deprecated use `GetChatbotAnalyticsResponse$inboundSchema` instead. */
    export const inboundSchema = GetChatbotAnalyticsResponse$inboundSchema;
    /** @deprecated use `GetChatbotAnalyticsResponse$outboundSchema` instead. */
    export const outboundSchema = GetChatbotAnalyticsResponse$outboundSchema;
    /** @deprecated use `GetChatbotAnalyticsResponse$Outbound` instead. */
    export type Outbound = GetChatbotAnalyticsResponse$Outbound;
}
