/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetChatChatIdRequest = {
    chatId: string;
};

/**
 * OK
 */
export type GetChatChatIdResponseBody = {};

export type GetChatChatIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: GetChatChatIdResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetChatChatIdRequest$ {
    export const inboundSchema: z.ZodType<GetChatChatIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            chat_id: z.string(),
        })
        .transform((v) => {
            return {
                chatId: v.chat_id,
            };
        });

    export type Outbound = {
        chat_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChatChatIdRequest> = z
        .object({
            chatId: z.string(),
        })
        .transform((v) => {
            return {
                chat_id: v.chatId,
            };
        });
}

/** @internal */
export namespace GetChatChatIdResponseBody$ {
    export const inboundSchema: z.ZodType<GetChatChatIdResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChatChatIdResponseBody> =
        z.object({});
}

/** @internal */
export namespace GetChatChatIdResponse$ {
    export const inboundSchema: z.ZodType<GetChatChatIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetChatChatIdResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetChatChatIdResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChatChatIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetChatChatIdResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
