/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetDocumentBrainIdDocumentIdDownloadRequest = {
    brainId: string;
    documentId: string;
};

/**
 * OK
 */
export type GetDocumentBrainIdDocumentIdDownloadResponseBody = {};

export type GetDocumentBrainIdDocumentIdDownloadResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: GetDocumentBrainIdDocumentIdDownloadResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetDocumentBrainIdDocumentIdDownloadRequest$ {
    export const inboundSchema: z.ZodType<
        GetDocumentBrainIdDocumentIdDownloadRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            brain_id: z.string(),
            document_id: z.string(),
        })
        .transform((v) => {
            return {
                brainId: v.brain_id,
                documentId: v.document_id,
            };
        });

    export type Outbound = {
        brain_id: string;
        document_id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetDocumentBrainIdDocumentIdDownloadRequest
    > = z
        .object({
            brainId: z.string(),
            documentId: z.string(),
        })
        .transform((v) => {
            return {
                brain_id: v.brainId,
                document_id: v.documentId,
            };
        });
}

/** @internal */
export namespace GetDocumentBrainIdDocumentIdDownloadResponseBody$ {
    export const inboundSchema: z.ZodType<
        GetDocumentBrainIdDocumentIdDownloadResponseBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetDocumentBrainIdDocumentIdDownloadResponseBody
    > = z.object({});
}

/** @internal */
export namespace GetDocumentBrainIdDocumentIdDownloadResponse$ {
    export const inboundSchema: z.ZodType<
        GetDocumentBrainIdDocumentIdDownloadResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z
                .lazy(() => GetDocumentBrainIdDocumentIdDownloadResponseBody$.inboundSchema)
                .optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetDocumentBrainIdDocumentIdDownloadResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetDocumentBrainIdDocumentIdDownloadResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z
                .lazy(() => GetDocumentBrainIdDocumentIdDownloadResponseBody$.outboundSchema)
                .optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
