/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetIntegrationIntegrationNameListRequest = {
    /**
     * Currently supported integrations are "notion" and "confluence". More integrations will be added in the future.
     */
    integrationName: string;
};

/**
 * OK
 */
export type GetIntegrationIntegrationNameListResponseBody = {};

export type GetIntegrationIntegrationNameListResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: GetIntegrationIntegrationNameListResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace GetIntegrationIntegrationNameListRequest$ {
    export const inboundSchema: z.ZodType<
        GetIntegrationIntegrationNameListRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            integration_name: z.string(),
        })
        .transform((v) => {
            return {
                integrationName: v.integration_name,
            };
        });

    export type Outbound = {
        integration_name: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetIntegrationIntegrationNameListRequest
    > = z
        .object({
            integrationName: z.string(),
        })
        .transform((v) => {
            return {
                integration_name: v.integrationName,
            };
        });
}

/** @internal */
export namespace GetIntegrationIntegrationNameListResponseBody$ {
    export const inboundSchema: z.ZodType<
        GetIntegrationIntegrationNameListResponseBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetIntegrationIntegrationNameListResponseBody
    > = z.object({});
}

/** @internal */
export namespace GetIntegrationIntegrationNameListResponse$ {
    export const inboundSchema: z.ZodType<
        GetIntegrationIntegrationNameListResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z
                .lazy(() => GetIntegrationIntegrationNameListResponseBody$.inboundSchema)
                .optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetIntegrationIntegrationNameListResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetIntegrationIntegrationNameListResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z
                .lazy(() => GetIntegrationIntegrationNameListResponseBody$.outboundSchema)
                .optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
