/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PostIntegrationIntegrationNameAddRequestBody = {};

export type PostIntegrationIntegrationNameAddRequest = {
    /**
     * notion / confluence
     */
    integrationName: string;
    requestBody?: PostIntegrationIntegrationNameAddRequestBody | undefined;
};

/**
 * OK
 */
export type PostIntegrationIntegrationNameAddResponseBody = {};

export type PostIntegrationIntegrationNameAddResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: PostIntegrationIntegrationNameAddResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PostIntegrationIntegrationNameAddRequestBody$ {
    export const inboundSchema: z.ZodType<
        PostIntegrationIntegrationNameAddRequestBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostIntegrationIntegrationNameAddRequestBody
    > = z.object({});
}

/** @internal */
export namespace PostIntegrationIntegrationNameAddRequest$ {
    export const inboundSchema: z.ZodType<
        PostIntegrationIntegrationNameAddRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            integration_name: z.string(),
            RequestBody: z
                .lazy(() => PostIntegrationIntegrationNameAddRequestBody$.inboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                integrationName: v.integration_name,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        integration_name: string;
        RequestBody?: PostIntegrationIntegrationNameAddRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostIntegrationIntegrationNameAddRequest
    > = z
        .object({
            integrationName: z.string(),
            requestBody: z
                .lazy(() => PostIntegrationIntegrationNameAddRequestBody$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                integration_name: v.integrationName,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace PostIntegrationIntegrationNameAddResponseBody$ {
    export const inboundSchema: z.ZodType<
        PostIntegrationIntegrationNameAddResponseBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostIntegrationIntegrationNameAddResponseBody
    > = z.object({});
}

/** @internal */
export namespace PostIntegrationIntegrationNameAddResponse$ {
    export const inboundSchema: z.ZodType<
        PostIntegrationIntegrationNameAddResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z
                .lazy(() => PostIntegrationIntegrationNameAddResponseBody$.inboundSchema)
                .optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: PostIntegrationIntegrationNameAddResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostIntegrationIntegrationNameAddResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z
                .lazy(() => PostIntegrationIntegrationNameAddResponseBody$.outboundSchema)
                .optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
