/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type PostChatbotCreateRequestBody = {
    /**
     * The name of the chatbot
     */
    name: string;
    /**
     * The ID of the brain associated with the chatbot
     */
    brainId: string;
    urls: Array<string>;
};

export type PostChatbotCreateResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    chatbotResponses?: Array<components.ChatbotResponse> | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PostChatbotCreateRequestBody$ {
    export const inboundSchema: z.ZodType<PostChatbotCreateRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            name: z.string(),
            brain_id: z.string(),
            urls: z.array(z.string()),
        })
        .transform((v) => {
            return remap$(v, {
                brain_id: "brainId",
            });
        });

    export type Outbound = {
        name: string;
        brain_id: string;
        urls: Array<string>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatbotCreateRequestBody> = z
        .object({
            name: z.string(),
            brainId: z.string(),
            urls: z.array(z.string()),
        })
        .transform((v) => {
            return remap$(v, {
                brainId: "brain_id",
            });
        });
}

/** @internal */
export namespace PostChatbotCreateResponse$ {
    export const inboundSchema: z.ZodType<PostChatbotCreateResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            ChatbotResponses: z.array(components.ChatbotResponse$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                ChatbotResponses: "chatbotResponses",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        ChatbotResponses?: Array<components.ChatbotResponse$.Outbound> | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatbotCreateResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            chatbotResponses: z.array(components.ChatbotResponse$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                chatbotResponses: "ChatbotResponses",
                headers: "Headers",
            });
        });
}
