/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PostChatGetResponseRequestBody = {
    /**
     * Id of chat to which you want to send message
     */
    chatThreadId?: string | undefined;
    /**
     * message
     */
    text?: string | undefined;
};

export type PostChatGetResponseResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    chatInteraction?: components.ChatInteraction | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PostChatGetResponseRequestBody$ {
    export const inboundSchema: z.ZodType<PostChatGetResponseRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            chat_thread_id: z.string().optional(),
            text: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.chat_thread_id === undefined ? null : { chatThreadId: v.chat_thread_id }),
                ...(v.text === undefined ? null : { text: v.text }),
            };
        });

    export type Outbound = {
        chat_thread_id?: string | undefined;
        text?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatGetResponseRequestBody> =
        z
            .object({
                chatThreadId: z.string().optional(),
                text: z.string().optional(),
            })
            .transform((v) => {
                return {
                    ...(v.chatThreadId === undefined ? null : { chat_thread_id: v.chatThreadId }),
                    ...(v.text === undefined ? null : { text: v.text }),
                };
            });
}

/** @internal */
export namespace PostChatGetResponseResponse$ {
    export const inboundSchema: z.ZodType<PostChatGetResponseResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            ChatInteraction: components.ChatInteraction$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.ChatInteraction === undefined
                    ? null
                    : { chatInteraction: v.ChatInteraction }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        ChatInteraction?: components.ChatInteraction$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatGetResponseResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            chatInteraction: components.ChatInteraction$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.chatInteraction === undefined
                    ? null
                    : { ChatInteraction: v.chatInteraction }),
                Headers: v.headers,
            };
        });
}
