/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PostDocumentBrainIdUrlRequestBody = {};

export type PostDocumentBrainIdUrlRequest = {
    brainId: string;
    requestBody?: PostDocumentBrainIdUrlRequestBody | undefined;
};

/**
 * OK
 */
export type PostDocumentBrainIdUrlResponseBody = {};

export type PostDocumentBrainIdUrlResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: PostDocumentBrainIdUrlResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PostDocumentBrainIdUrlRequestBody$ {
    export const inboundSchema: z.ZodType<
        PostDocumentBrainIdUrlRequestBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostDocumentBrainIdUrlRequestBody
    > = z.object({});
}

/** @internal */
export namespace PostDocumentBrainIdUrlRequest$ {
    export const inboundSchema: z.ZodType<PostDocumentBrainIdUrlRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
            RequestBody: z.lazy(() => PostDocumentBrainIdUrlRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                brainId: v.brain_id,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        brain_id: string;
        RequestBody?: PostDocumentBrainIdUrlRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostDocumentBrainIdUrlRequest> =
        z
            .object({
                brainId: z.string(),
                requestBody: z
                    .lazy(() => PostDocumentBrainIdUrlRequestBody$.outboundSchema)
                    .optional(),
            })
            .transform((v) => {
                return {
                    brain_id: v.brainId,
                    ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
                };
            });
}

/** @internal */
export namespace PostDocumentBrainIdUrlResponseBody$ {
    export const inboundSchema: z.ZodType<
        PostDocumentBrainIdUrlResponseBody,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostDocumentBrainIdUrlResponseBody
    > = z.object({});
}

/** @internal */
export namespace PostDocumentBrainIdUrlResponse$ {
    export const inboundSchema: z.ZodType<PostDocumentBrainIdUrlResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => PostDocumentBrainIdUrlResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: PostDocumentBrainIdUrlResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostDocumentBrainIdUrlResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                object: z.lazy(() => PostDocumentBrainIdUrlResponseBody$.outboundSchema).optional(),
                headers: z.record(z.array(z.string())),
            })
            .transform((v) => {
                return {
                    HttpMeta: v.httpMeta,
                    ...(v.object === undefined ? null : { object: v.object }),
                    Headers: v.headers,
                };
            });
}
