/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

/**
 * The integration to use for the chat
 */
export enum Integration {
    Files = "files",
    DataWarehouse = "data-warehouse",
}

export type PostChatRequestBody = {
    /**
     * The ID of the brain to associate with the chat
     */
    brainId: string;
    /**
     * The name of the chat
     */
    name: string;
    /**
     * The integration to use for the chat
     */
    integration?: Integration | undefined;
};

export type PostChatResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * CREATED
     */
    chat?: components.Chat | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace Integration$ {
    export const inboundSchema = z.nativeEnum(Integration);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace PostChatRequestBody$ {
    export const inboundSchema: z.ZodType<PostChatRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
            name: z.string(),
            integration: Integration$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                brainId: v.brain_id,
                name: v.name,
                ...(v.integration === undefined ? null : { integration: v.integration }),
            };
        });

    export type Outbound = {
        brain_id: string;
        name: string;
        integration?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatRequestBody> = z
        .object({
            brainId: z.string(),
            name: z.string(),
            integration: Integration$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                brain_id: v.brainId,
                name: v.name,
                ...(v.integration === undefined ? null : { integration: v.integration }),
            };
        });
}

/** @internal */
export namespace PostChatResponse$ {
    export const inboundSchema: z.ZodType<PostChatResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Chat: components.Chat$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Chat === undefined ? null : { chat: v.Chat }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Chat?: components.Chat$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            chat: components.Chat$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.chat === undefined ? null : { Chat: v.chat }),
                Headers: v.headers,
            };
        });
}
