/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PostChatbotDeleteRequest = {
    chatbotId?: string | undefined;
};

/**
 * OK
 */
export type PostChatbotDeleteResponseBody = {};

export type PostChatbotDeleteResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: PostChatbotDeleteResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PostChatbotDeleteRequest$ {
    export const inboundSchema: z.ZodType<PostChatbotDeleteRequest, z.ZodTypeDef, unknown> = z
        .object({
            chatbot_id: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.chatbot_id === undefined ? null : { chatbotId: v.chatbot_id }),
            };
        });

    export type Outbound = {
        chatbot_id?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatbotDeleteRequest> = z
        .object({
            chatbotId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.chatbotId === undefined ? null : { chatbot_id: v.chatbotId }),
            };
        });
}

/** @internal */
export namespace PostChatbotDeleteResponseBody$ {
    export const inboundSchema: z.ZodType<PostChatbotDeleteResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatbotDeleteResponseBody> =
        z.object({});
}

/** @internal */
export namespace PostChatbotDeleteResponse$ {
    export const inboundSchema: z.ZodType<PostChatbotDeleteResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => PostChatbotDeleteResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: PostChatbotDeleteResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostChatbotDeleteResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => PostChatbotDeleteResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
