/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type PutBrainBrainIdRequestBody = {
    /**
     * Updated name of the brain
     */
    name: string;
};

export type PutBrainBrainIdRequest = {
    brainId: string;
    requestBody?: PutBrainBrainIdRequestBody | undefined;
};

export type PutBrainBrainIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    brain?: components.Brain | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PutBrainBrainIdRequestBody$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdRequestBody, z.ZodTypeDef, unknown> =
        z.object({
            name: z.string(),
        });

    export type Outbound = {
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdRequestBody> =
        z.object({
            name: z.string(),
        });
}

/** @internal */
export namespace PutBrainBrainIdRequest$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
            RequestBody: z.lazy(() => PutBrainBrainIdRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                brain_id: "brainId",
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        brain_id: string;
        RequestBody?: PutBrainBrainIdRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdRequest> = z
        .object({
            brainId: z.string(),
            requestBody: z.lazy(() => PutBrainBrainIdRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                brainId: "brain_id",
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace PutBrainBrainIdResponse$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Brain: components.Brain$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Brain: "brain",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Brain?: components.Brain$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            brain: components.Brain$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                brain: "Brain",
                headers: "Headers",
            });
        });
}
