/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PutBrainBrainIdRequestBody = {};

export type PutBrainBrainIdRequest = {
    brainId: string;
    requestBody?: PutBrainBrainIdRequestBody | undefined;
};

/**
 * OK
 */
export type PutBrainBrainIdResponseBody = {};

export type PutBrainBrainIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    object?: PutBrainBrainIdResponseBody | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace PutBrainBrainIdRequestBody$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdRequestBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdRequestBody> =
        z.object({});
}

/** @internal */
export namespace PutBrainBrainIdRequest$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            brain_id: z.string(),
            RequestBody: z.lazy(() => PutBrainBrainIdRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                brainId: v.brain_id,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        brain_id: string;
        RequestBody?: PutBrainBrainIdRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdRequest> = z
        .object({
            brainId: z.string(),
            requestBody: z.lazy(() => PutBrainBrainIdRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                brain_id: v.brainId,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace PutBrainBrainIdResponseBody$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdResponseBody, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdResponseBody> =
        z.object({});
}

/** @internal */
export namespace PutBrainBrainIdResponse$ {
    export const inboundSchema: z.ZodType<PutBrainBrainIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => PutBrainBrainIdResponseBody$.inboundSchema).optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: PutBrainBrainIdResponseBody$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutBrainBrainIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => PutBrainBrainIdResponseBody$.outboundSchema).optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
                Headers: v.headers,
            };
        });
}
